import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], weight: "700" });

export const metadata: Metadata = {
  title: "Tic-Tac-Toe NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"${montserrat.className} antialiased"}>
        {children}
        <footer className="py-10 flex justify-center items-center">
          Test of layout and routing
        </footer>
      </body>
    </html>
  );
}
